FROM openpilot:stage2

RUN cd /root/openpilot && git pull origin master && git submodule update --recursive
RUN sed -i -e "s/CPUExecutionProvider/CUDAExecutionProvider/g" /root/openpilot/selfdrive/modeld/runners/onnx_runner.py
RUN USE_WEBCAM=1 scons -j$(nproc)
